import { letterCombinations } from "@daily";

describe("18", () => {
  test.each([
    {
      digits: "23",
      expected: ["ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf"],
    },
    {
      digits: "",
      expected: [],
    },
    {
      digits: "2",
      expected: ["a", "b", "c"],
    },
    {
      digits: "234",
      expected: [
        "adg",
        "adh",
        "adi",
        "aeg",
        "aeh",
        "aei",
        "afg",
        "afh",
        "afi",
        "bdg",
        "bdh",
        "bdi",
        "beg",
        "beh",
        "bei",
        "bfg",
        "bfh",
        "bfi",
        "cdg",
        "cdh",
        "cdi",
        "ceg",
        "ceh",
        "cei",
        "cfg",
        "cfh",
        "cfi",
      ],
    },
    {
      digits: "237",
      expected: [
        "adp",
        "adq",
        "adr",
        "ads",
        "aep",
        "aeq",
        "aer",
        "aes",
        "afp",
        "afq",
        "afr",
        "afs",

        "bdp",
        "bdq",
        "bdr",
        "bds",
        "bep",
        "beq",
        "ber",
        "bes",
        "bfp",
        "bfq",
        "bfr",
        "bfs",

        "cdp",
        "cdq",
        "cdr",
        "cds",
        "cep",
        "ceq",
        "cer",
        "ces",
        "cfp",
        "cfq",
        "cfr",
        "cfs",
      ],
    },
  ])("", ({ digits, expected }) => {
    expect(letterCombinations(digits)).toEqual(expected);
  });
});
